version: "2"
services:
  web:
    image: nginx:alpine
    command: nginx
    restart: always
    ports:
      - "80:80/tcp"
    links:
      - app
    volumes_from:
      - app
    depends_on:
      - app
  app:
    image: slavoutich/nextcloud:latest
    restart: always
    expose:
      - "9000"
    links:
      - redis
      - pgsql
    volumes_from:
      - storage
    depends_on:
      - redis
      - pgsql
  redis:
    image: redis:3.0-alpine
    restart: always
    expose:
      - 6379
  pgsql:
    image: postgres:9.6-alpine
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/9.6
    volumes_from:
      - storage
  storage:
    image: alpine:latest
    command: /bin/sh
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/data/nextcloud/config:/var/www/html/config
      - /mnt/data/nextcloud/data:/var/www/html/data
      - /mnt/data/nextcloud/apps:/var/www/html/apps
      - /mnt/data/nextcloud/pgdb:/var/lib/postgresql/data
      - /mnt/data/backup:/var/backup
